<?php

namespace App\Imports;

use App\Models\AcademicYear;
use App\Models\Classroom;
use App\Models\Student;
use Carbon\Carbon;
use Illuminate\Support\Facades\Log;
use Maatwebsite\Excel\Concerns\ToModel;
use Maatwebsite\Excel\Concerns\WithHeadingRow;

/**
 * Import students from Excel.
 *
 * Expected header row (row 1):
 *   Nom Complet | Date Naissance | Genre | Code Classe | Section
 *
 * Matricule is auto-generated by the Student model.
 * Section is optional when included in Code Classe (e.g. "CPA" → CP + A).
 * Dates: D/M/YYYY, DD/MM/YYYY, YYYY-MM-DD, or Excel numeric serial.
 */
class StudentsImport implements ToModel, WithHeadingRow
{
    public int   $imported     = 0;
    public int   $skipped      = 0;
    public int   $updated      = 0;
    public array $importErrors = [];

    /** Tracks "classroom_id:normalized_name" seen in this import batch to catch intra-file duplicates. */
    private array $seenInBatch = [];

    public function model(array $row): ?Student
    {
        // Skip fully empty rows
        if (empty(array_filter(array_values($row), fn($v) => $v !== null && $v !== ''))) {
            return null;
        }

        try {
            $fullName = trim((string) ($row['nom_complet'] ?? ''));
            $genre    = strtoupper(trim((string) ($row['genre'] ?? '')));

            if (!$fullName) {
                $this->importErrors[] = "Nom complet manquant";
                $this->skipped++;
                return null;
            }

            if (!in_array($genre, ['M', 'F'])) {
                $this->importErrors[] = "Genre invalide pour : {$fullName} (attendu M ou F)";
                $this->skipped++;
                return null;
            }

            // ── Classroom ─────────────────────────────────────────────────────
            [$code, $section] = $this->resolveClassCode(
                trim((string) ($row['code_classe'] ?? '')),
                trim((string) ($row['section']     ?? ''))
            );

            $classroom = Classroom::where('code', $code)->where('section', $section)->first();

            if (!$classroom) {
                $this->importErrors[] = "Classe introuvable « {$code} {$section} » pour : {$fullName}";
                $this->skipped++;
                return null;
            }

            // ── Academic year ─────────────────────────────────────────────────
            $year = AcademicYear::where('is_current', true)->first();
            if (!$year) {
                $this->importErrors[] = "Aucune année scolaire courante";
                $this->skipped++;
                return null;
            }

            // ── Birth date ────────────────────────────────────────────────────
            $birthDate = $this->parseBirthDate($row['date_naissance'] ?? null);
            if (!$birthDate) {
                $this->importErrors[] = "Date invalide pour : {$fullName}";
                $this->skipped++;
                return null;
            }

            // ── Duplicate check: in this file ────────────────────────────────
            $key = $classroom->id . ':' . mb_strtolower(preg_replace('/\s+/', ' ', $fullName));

            if (isset($this->seenInBatch[$key])) {
                $this->importErrors[] = "Doublon dans le fichier : « {$fullName} » déjà présent dans {$classroom->label}";
                $this->skipped++;
                return null;
            }

            // ── Duplicate check: in database ──────────────────────────────────
            $existsInDb = Student::where('classroom_id', $classroom->id)
                ->whereRaw('LOWER(full_name) = ?', [mb_strtolower($fullName)])
                ->exists();

            if ($existsInDb) {
                $this->importErrors[] = "Déjà en base : « {$fullName} » existe déjà dans {$classroom->label}";
                $this->skipped++;
                return null;
            }

            $this->seenInBatch[$key] = true;

            // ── Insert (matricule auto-generated by Student::boot) ────────────
            $this->imported++;

            return new Student([
                'full_name'        => $fullName,
                'birth_date'       => $birthDate,
                'gender'           => $genre,
                'classroom_id'     => $classroom->id,
                'academic_year_id' => $year->id,
            ]);

        } catch (\Throwable $e) {
            $this->importErrors[] = "Erreur : " . $e->getMessage();
            Log::error('StudentsImport', ['row' => $row, 'error' => $e->getMessage()]);
            $this->skipped++;
            return null;
        }
    }

    /** "CPA" → ["CP","A"]  |  "CE2B" → ["CE2","B"]  |  "CP"+"A" → ["CP","A"] */
    private function resolveClassCode(string $code, string $section): array
    {
        if ($section !== '') {
            return [strtoupper($code), strtoupper($section)];
        }
        if (strlen($code) > 1 && ctype_alpha(substr($code, -1))) {
            return [strtoupper(substr($code, 0, -1)), strtoupper(substr($code, -1))];
        }
        return [strtoupper($code), ''];
    }

    /** Accepts D/M/YYYY, DD/MM/YYYY, YYYY-MM-DD, DD-MM-YYYY, Excel serial. */
    private function parseBirthDate(mixed $v): ?string
    {
        if ($v === null || $v === '') return null;

        // Excel numeric serial
        if (is_numeric($v) && $v > 1000) {
            try { return Carbon::createFromTimestamp(($v - 25569) * 86400)->format('Y-m-d'); }
            catch (\Throwable) {}
        }

        $s = trim((string) $v);

        foreach (['j/n/Y', 'd/m/Y', 'Y-m-d', 'j-n-Y', 'd-m-Y'] as $fmt) {
            try { return Carbon::createFromFormat($fmt, $s)->format('Y-m-d'); }
            catch (\Throwable) {}
        }

        try { return Carbon::parse($s)->format('Y-m-d'); }
        catch (\Throwable) {
            Log::warning('StudentsImport: bad date', ['input' => $v]);
            return null;
        }
    }

    public function getStats(): array
    {
        return [
            'imported' => $this->imported,
            'updated'  => $this->updated,
            'skipped'  => $this->skipped,
            'errors'   => $this->importErrors,
        ];
    }
}
