<?php

namespace App\Imports;

use App\Models\AcademicYear;
use App\Models\Classroom;
use App\Models\Student;
use Carbon\Carbon;
use Illuminate\Support\Facades\Log;
use Maatwebsite\Excel\Concerns\ToModel;
use Maatwebsite\Excel\Concerns\WithHeadingRow;

/**
 * Import students from Excel.
 *
 * Expected header row (row 1):
 *   Nom Complet | Date Naissance | Genre | Code Classe | Section
 *
 * Matricule is auto-generated by the Student model.
 * Section is optional when included in Code Classe (e.g. "CPA" → CP + A).
 * Dates: D/M/YYYY, DD/MM/YYYY, YYYY-MM-DD, or Excel numeric serial.
 */
class StudentsImport implements ToModel, WithHeadingRow
{
    public int   $imported      = 0;
    public int   $skipped       = 0;
    public int   $duplicates    = 0;   // silent: same name in same file
    public int   $alreadyInDb   = 0;   // silent: already exists in DB
    public array $importErrors  = [];

    /** Tracks "classroom_id:normalized_name" seen in this import batch to catch intra-file duplicates. */
    private array $seenInBatch = [];

    public function model(array $row): ?Student
    {
        // Skip fully empty rows
        if (empty(array_filter(array_values($row), fn($v) => $v !== null && $v !== ''))) {
            return null;
        }

        try {
            $fullName = trim((string) ($row['nom_complet'] ?? ''));
            $genre    = strtoupper(trim((string) ($row['genre'] ?? '')));

            if (!$fullName) {
                $this->importErrors[] = "Nom complet manquant";
                $this->skipped++;
                return null;
            }

            if (!in_array($genre, ['M', 'F'])) {
                $this->importErrors[] = "Genre invalide pour : {$fullName} (attendu M ou F)";
                $this->skipped++;
                return null;
            }

            // ── Classroom ─────────────────────────────────────────────────────
            [$code, $section] = $this->resolveClassCode(
                trim((string) ($row['code_classe'] ?? '')),
                trim((string) ($row['section']     ?? ''))
            );

            // Try exact match first, then hyphen-combined (e.g. "PS"+"A" → code="PS-A")
            $classroom = Classroom::where('code', '=', $code, 'and')->where('section', '=', $section, 'and')->first()
                ?? ($section !== ''
                    ? Classroom::where('code', '=', $code . '-' . $section, 'and')->where('section', '=', $section, 'and')->first()
                    : null);

            if (!$classroom) {
                $this->importErrors[] = "Classe introuvable « {$code} {$section} » pour : {$fullName}";
                $this->skipped++;
                return null;
            }

            // ── Academic year ─────────────────────────────────────────────────
            $year = AcademicYear::where('is_current', '=', true, 'and')->first();
            if (!$year) {
                $this->importErrors[] = "Aucune année scolaire courante";
                $this->skipped++;
                return null;
            }

            // ── Birth date ────────────────────────────────────────────────────
            $birthDate = $this->parseBirthDate($row['date_naissance'] ?? null);
            if (!$birthDate) {
                $this->importErrors[] = "Date invalide pour : {$fullName}";
                $this->skipped++;
                return null;
            }

            // ── Duplicate: same name + same class + same birth date (in this file) ──────
            $key = $classroom->id . ':' . mb_strtolower(preg_replace('/\s+/', ' ', $fullName)) . ':' . $birthDate;

            if (isset($this->seenInBatch[$key])) {
                $this->duplicates++;
                return null;
            }

            // ── Duplicate: same name + same class + same birth date (in database) ────────
            $existsInDb = Student::where('classroom_id', '=', $classroom->id, 'and')
                ->whereRaw('LOWER(full_name) = ?', [mb_strtolower($fullName)])
                ->where('birth_date', '=', $birthDate, 'and')
                ->exists();

            if ($existsInDb) {
                $this->alreadyInDb++;
                return null;
            }

            $this->seenInBatch[$key] = true;

            // ── Insert (matricule auto-generated by Student::boot) ────────────
            $this->imported++;

            return new Student([
                'full_name'        => $fullName,
                'birth_date'       => $birthDate,
                'gender'           => $genre,
                'classroom_id'     => $classroom->id,
                'academic_year_id' => $year->id,
            ]);

        } catch (\Throwable $e) {
            $this->importErrors[] = "Erreur : " . $e->getMessage();
            Log::error('StudentsImport', ['row' => $row, 'error' => $e->getMessage()]);
            $this->skipped++;
            return null;
        }
    }

    /**
     * Resolve classroom code + section from various formats:
     *   "PS-A" + ""  → ["PS","A"]
     *   "PS-A" + "A" → ["PS","A"]
     *   "CPA"  + ""  → ["CP","A"]
     *   "CE2B" + ""  → ["CE2","B"]
     *   "CP"   + "A" → ["CP","A"]
     */
    private function resolveClassCode(string $code, string $section): array
    {
        // "CE2 A", "PS A" — space-separated in the same cell
        if (str_contains($code, ' ')) {
            $parts  = explode(' ', $code, 2);
            $base   = strtoupper(trim($parts[0]));
            $suffix = strtoupper(trim($parts[1]));
            return [$base, $section !== '' ? strtoupper($section) : $suffix];
        }

        // "PS-A", "CE2-B" — hyphen-separated
        if (str_contains($code, '-')) {
            $parts  = explode('-', $code, 2);
            $base   = strtoupper($parts[0]);
            $suffix = strtoupper($parts[1]);
            return [$base, $section !== '' ? strtoupper($section) : $suffix];
        }

        if ($section !== '') {
            return [strtoupper($code), strtoupper($section)];
        }

        // "CPA" → ["CP","A"], "CE2B" → ["CE2","B"]
        if (strlen($code) > 1 && ctype_alpha(substr($code, -1))) {
            return [strtoupper(substr($code, 0, -1)), strtoupper(substr($code, -1))];
        }

        return [strtoupper($code), ''];
    }

    /** Accepts D/M/YYYY, DD/MM/YYYY, YYYY-MM-DD, DD-MM-YYYY, Excel serial. */
    private function parseBirthDate(mixed $v): ?string
    {
        if ($v === null || $v === '') return null;

        $currentYear = (int) date('Y');

        // Excel numeric serial (PhpSpreadsheet's own converter avoids manual formula errors)
        if (is_numeric($v) && (float) $v > 1000) {
            try {
                $dt = \PhpOffice\PhpSpreadsheet\Shared\Date::excelToDateTimeObject((float) $v);
                $year = (int) $dt->format('Y');
                if ($year >= 1990 && $year <= $currentYear) {
                    return $dt->format('Y-m-d');
                }
            } catch (\Throwable) {}
            // Serial didn't yield a valid school-age date — fall through to string parse
        }

        $s = trim((string) $v);
        // Collapse spaces around separators: "31 /01/2021" → "31/01/2021"
        $s = preg_replace('/\s*([\/\-\.])\s*/', '$1', $s);
        // Normalize dot separators to slashes: "28.11.2022" → "28/11/2022"
        if (preg_match('/^\d{1,2}\.\d{1,2}\.\d{2,4}$/', $s)) {
            $s = str_replace('.', '/', $s);
        }
        // Normalize 2-digit years: "28/11/22" → "28/11/2022"
        $s = preg_replace('/^(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{2})$/', '$1/$2/20$3', $s);

        foreach (['j/n/Y', 'd/m/Y', 'Y-m-d', 'j-n-Y', 'd-m-Y', 'Y/m/d', 'Y/n/j'] as $fmt) {
            try {
                $date = Carbon::createFromFormat($fmt, $s);
                $year = (int) $date->format('Y');
                if ($year >= 1990 && $year <= $currentYear) {
                    return $date->format('Y-m-d');
                }
            } catch (\Throwable) {}
        }

        // Last-resort parse — only accept if year is in reasonable range
        try {
            $date = Carbon::parse($s);
            $year = (int) $date->format('Y');
            if ($year >= 1990 && $year <= $currentYear) {
                return $date->format('Y-m-d');
            }
        } catch (\Throwable) {}

        Log::warning('StudentsImport: bad date', ['raw' => $v, 'normalized' => $s]);
        return null;
    }

    public function getStats(): array
    {
        return [
            'imported'    => $this->imported,
            'duplicates'  => $this->duplicates,
            'alreadyInDb' => $this->alreadyInDb,
            'skipped'     => $this->skipped,
            'errors'      => $this->importErrors,
        ];
    }
}
